version: "3.9"
services:
  api:
    build: ./images/api
    image: mohamedmankouchi/storypathapi
    environment:
      MONGO_URL:
      PORT:
      ACCES_TOKEN_SECRET:
    ports:
      - 80:80
    volumes:
      - ./images/api/src:/usr/app/src
